service: cowin-notification-service
app: cowin-notification-service
org: reziba

frameworkVersion: '2'

custom:
  secrets: ${file(secrets.${opt:stage, self:provider.stage}.yml)}

provider:
  name: aws
  runtime: python3.8
  timeout: 5
  memorySize: 128
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-south-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
            - cloudwatch:*
            - sqs:*
            - ses:*
            - lambda:*
          Resource: '*'
  environment:
      DB_HOSTNAME: ${self:custom.secrets.DB_HOSTNAME}
      DB_PASSWORD: ${self:custom.secrets.DB_PASSWORD}
      DB_PORT: ${self:custom.secrets.DB_PORT}
      DB_USER: ${self:custom.secrets.DB_USER}
      DB_NAME: ${self:custom.secrets.DB_NAME}
      COWIN_URL: ${self:custom.secrets.COWIN_URL}
#      NOTIF_QUEUE_URL: !Ref NotificationQueue
      SENDER_EMAIL: ${self:custom.secrets.SENDER_EMAIL}
      WEBSITE_URL: ${self:custom.secrets.WEBSITE_URL}
      DUMMY: 'abc'
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-python-requirements
  - serverless-secrets-plugin

package:
  individually: true
  exclude:
    - venv/**
    - node_modules/**
    - frontend/**
    - scripts/**

functions:
  get_states:
    handler: handler.get_states
    events:
      - http:
          path: /states
          method: get

  get_districts:
    handler: handler.get_districts
    events:
      - http:
          path: /districts
          method: get

  get_centers:
    handler: handler.get_centers
    events:
      - http:
          path: /centers
          method: get

  get_district_preferences:
    handler: handler.get_district_preferences
    events:
      - http:
          path: /centers/preferences
          method: get

  subscribe:
    handler: handler.subscribe
    events:
      - http:
          path: /subscribe
          method: post
          cors: true

  unsubscribe:
    handler: handler.unsubscribe
    events:
      - http:
          path: /unsubscribe
          method: post
          cors: true

  trigger_district_updates:
    handler: handler.trigger_district_updates
    timeout: 20
    maximumRetryAttempts: 0
    maximumEventAge: 60

  update_district_slots:
    handler: handler.update_district_slots
    timeout: 20
    maximumRetryAttempts: 0
    maximumEventAge: 60

  notif_dispatcher:
    handler: handler.notif_dispatcher
    timeout: 60
    maximumRetryAttempts: 0
    maximumEventAge: 60
  #    events:
#      - sqs:
#          arn: !GetAtt NotificationQueue.Arn
#          batchSize: 5

  send_batch_email:
    handler: handler.send_batch_email
    timeout: 60
    maximumRetryAttempts: 0
    maximumEventAge: 60

  verify_email:
    handler: handler.verify_email
    events:
      - http:
          path: /verify_email
          method: post
          cors: true

  test_email:
    handler: handler.test_email

  send_verification_email_manual:
    handler: handler.send_verification_email_manual

#resources:
#  Resources:
#    NotificationQueue:
#      Type: AWS::SQS::Queue
#      Properties:
#        VisibilityTimeout: 120
#        MessageRetentionPeriod: 120